name: Update Mono

on:
on:
  schedule:
    - cron: '15 21 * * *'
  push:


jobs:
  update-mono:
    runs-on: ubuntu-latest

    steps:
    - uses: pranavkm/blazorupdate@master
      with:
        github_token: ${{ secrets.PAT }}
